"""Export the validated control plan as finite kernel-checkable data.

This exporter is untrusted. The Lean checker uses the general compiler,
scale transitions and native word lengths, not Python implementations of
those functions. Freshness is checked against the complete committed plan.
The certificate concerns the logical stream, scales and work; physical
re-pairing of blank scalar ports remains outside this correspondence proof.
"""
from pathlib import Path

from . import codec
from .check_routes import check, require
from .verify import certify_plan

TARGET = codec.ROOT / "Lean/Geometry/SourceBankControl.lean"


def lean_list(items):
    return "[" + ",".join(items) + "]"


def render(packet):
    # Do not trust the plan's checksum or caller-supplied generation labels.
    n = 2
    program = [[[0,1],[0,0]], [[1,0],[]], [[0,1,0],[1]]]
    codec.equal(packet["program"], program, "kernel control program")
    _, routes = check(packet["routes"], n, 3, retain=True)
    plan = certify_plan(packet["plan"], program, routes)
    require(plan["input_bound"] == 2, "kernel control bound")
    rows = []
    for stage in plan["segments"]:
        generation, site, kind = stage["layer"], stage["site"], stage["kind"]
        if kind == "read":
            incoming = stage["polls"][-1]
            source = incoming["version"][1]
            carrier = 1 + ((generation - 1) % 2) * n + source
            op = f".transfer {carrier + 3} 3 {len(routes[carrier, 'read'])}"
        elif kind == "store":
            carrier = 1 + (generation % 2) * n + site
            op = f".transfer 0 {carrier + 3} {len(routes[carrier, 'write'])}"
        else:
            op = {"start": ".start", "add": ".add", "retire_operand": ".retire"}[kind]
        polls = []
        for sample in stage["polls"]:
            pair = sample["pair"]
            if pair == [2,1]:
                register = 0
            elif pair == [6,7]:
                register = 2
            elif set(pair) == {3,5}:
                register = 3
            else:
                carrier = min(pair) // 12
                require(set(pair) == {12*carrier,12*carrier+1}, "bank pair in kernel control")
                register = carrier + 3
            polls.append(f"({register},{sample['scale']})")
        cost = sum(len(block["edges"]) * block["repeat"] for block in stage["blocks"])
        rows.append(f"  ({op},{lean_list(polls)},{cost})")
    menus = lean_list("!" + lean_list(lean_list(map(str, ss)) for ss in layer) for layer in program)
    read_depths = lean_list(str(len(routes[c,"read"])) for c in range(1,2*n+1))
    write_depths = lean_list(str(len(routes[c,"write"])) for c in range(1,2*n+1))
    # These are the checked native publication outputs, not values
    # computed by an additional Python logical-machine implementation.
    payloads = [[a,b] for a in (-2,0,2) for b in (-2,0,2)]
    require(type(packet["cases"]) is list and len(packet["cases"]) == len(payloads), "kernel control cases")
    outputs = []
    for case, payload in zip(packet["cases"], payloads):
        codec.equal(case["payload"], payload, "kernel control payload inventory")
        values = case["stored_values"]
        require(type(values) is list and len(values) == 6 and all(type(v) is int for v in values),
                "kernel control stored outputs")
        outputs.append(lean_list(str(v) for v in values[-2:]))
    rendered_rows = ',\n'.join(rows)
    text = f'''import Geometry.SourceBankTrace

/-! Generated by `python -m source_native_programs.lean_control`.
Finite logical-stream, observed-scale, native-work and signed-output
correspondence with controls.json. Scalar-port embedding is not asserted. -/

set_option autoImplicit false
set_option maxRecDepth 4096

namespace OPH.SourceBankControl
open OPH.SourceBankMachine OPH.SourceBankTrace

def menus : List (Layer 2) := {menus}
def rd (i : ℕ) : ℕ := ({read_depths} : List ℕ)[i-4]?.getD 0
def wd (i : ℕ) : ℕ := ({write_depths} : List ℕ)[i-4]?.getD 0
def ops : List Op := program 2 rd wd false menus
def rows : List Row := [
{rendered_rows}
]

theorem captured_trace : checks {plan['cleanup_blocks']} ops (fun _ => 0) rows = true := by decide

theorem rejects_empty_trace : checks {plan['cleanup_blocks']} ops (fun _ => 0) [] = false := by decide
theorem rejects_missing_stage : checks {plan['cleanup_blocks']} ops (fun _ => 0) rows.dropLast = false := by decide
theorem rejects_extra_stage : checks {plan['cleanup_blocks']} ops (fun _ => 0) (rows ++ rows.take 1) = false := by decide
theorem rejects_wrong_instruction : checks {plan['cleanup_blocks']} ops (fun _ => 0)
    (rows.modify 0 fun r => (.retire,r.2)) = false := by decide
theorem rejects_undercharged_work : checks {plan['cleanup_blocks']} ops (fun _ => 0)
    (rows.modify 0 fun r => (r.1,r.2.1,r.2.2-1)) = false := by decide
theorem rejects_wrong_scale : checks {plan['cleanup_blocks']} ops (fun _ => 0)
    (rows.modify 0 fun r => (r.1,r.2.1.modify 0 (fun p => (p.1,p.2+1)),r.2.2)) = false := by decide

theorem captured_work : work ops {plan['cleanup_blocks']} (fun _ => 0) = {plan['scalar_means']} := by
  rw [checks_work _ _ _ _ captured_trace]
  decide

def initial (a b : ℤ) : Values := fun i =>
  if i = 2 then 1 else if i = 4 then a else if i = 5 then b else 0

theorem captured_signed_outputs :
    (([-2,0,2] : List ℤ).flatMap fun a => ([-2,0,2] : List ℤ).map fun b =>
      [values ops (initial a b) 6,values ops (initial a b) 7]) =
      {lean_list(outputs)} := by decide

end OPH.SourceBankControl
'''
    return text.encode("utf-8")


def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--controls", type=Path, default=codec.HERE/"controls.json")
    parser.add_argument("--output", type=Path, default=TARGET)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(codec.load_artifact(args.controls))
    if args.check:
        require(args.output.read_bytes() == content, "stale kernel control certificate")
    else:
        args.output.write_bytes(content)


if __name__ == "__main__":
    main()
