"""Independent reconstruction and adversarial controls for charged quantum transport."""

import copy
import itertools
import json
from pathlib import Path
import subprocess
import sys

import mpmath as mp
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from m1_quantum_transport import check, model, verify


@pytest.fixture(scope="module")
def evidence():
    return model.candidate()


def test_complete_independent_replay(evidence):
    check.verify_evidence(evidence)
    assert verify.verify()["evidence"] == evidence


MUTATIONS = [
    (("words", "012", "duration"), "1"),
    (("words", "012", "effective_speed"), "1"),
    (("words", "012", "speed_cap"), "3"),
    (("words", "012", "intermediate_events"), 0),
    (("words", "012", "history_sha256"), "0"*64),
    (("words", "012", "kernel", 0, 1, 0, 0, 0), "7"),
    (("spectra", "8", "modes"), 128),
    (("spectra", "8", "momenta"), True),
    (("spectra", "8", "rows", 17, 1, 0, 0), "1"),
    (("spectra", "8", "zero_points"), [[0, 0, 0]]),
    (("spectra", "8", "pi_points"), []),
    (("nodes", 0, "chirality"), -1),
    (("nodes", 0, "derivative", 0, 0), "3"),
    (("thermal", "16", "zero_momenta"), 1),
    (("thermal", "16", "cases", "1", 0), "0"),
    (("thermal", "16", "cases", "2", 1), "0"),
    (("fock", "3", "duration"), "1"),
    (("fock", "3", "full_fock_sha256"), "0"*64),
    (("fock", "3", "full_history_sha256"), "0"*64),
    (("fock", "3", "sector_dimensions", 2), 0),
    (("fock", "3", "one_particle", 1, 1, 1), "0"),
    (("budget", "isotropic", "velocity", 0, 0), "1"),
    (("budget", "waiting", "wait_time"), "0"),
    (("finite_delay", "pauli_basis", 5, 1, 8), "0"),
    (("finite_delay", "mixed_interaction_defect"), "0"),
    (("finite_delay", "signals", 0, 3), "0"),
    (("current", "spinors"), 0),
    (("current", "rows", 0, 2, 0), "0"),
    (("tetra", "flight_duration"), "1"),
    (("tetra", "field_speed"), "1"),
    (("tetra", "coin", 0, 1, 1), "1"),
    (("tetra", "bands", "1", "rank"), 4),
    (("tetra", "bands", "-1", "chirality"), 1),
    (("tetra", "bands", "1", "effects"), []),
    (("tetra", "spectrum", "modes"), 128),
    (("tetra", "spectrum", "pi_points"), []),
    (("tetra", "spectrum", "middle_points"), []),
    (("tetra", "thermal", "16", "modes"), 8192),
    (("tetra", "thermal", "4", "cases", "1", 0), "0"),
    (("tetra", "fock", "matrix_sha256"), "0"*64),
    (("tetra", "trajectories_sha256"), "0"*64),
    (("stencil", "polytopes", "tetrahedron", "geometric_ratio_squared"), "1"),
    (("stencil", "polytopes", "cube", "facets"), []),
    (("stencil", "polytopes", "cube", "cap_bound"), "1"),
    (("stencil", "velocities", "comparisons"), 0),
    (("stencil", "velocities", "derivatives_sha256"), "0"*64),
    (("tetra", "signals", 0, "probabilities", 0), "0"),
    (("tetra", "signals", 1, "time"), "3*sqrt(3)"),
    (("tetra", "signals", 3, "prepared"), []),
    (("stencil", "tilt_controls", "translation", "positive_centered_radius"), "0"),
    (("stencil", "tilt_controls", "translation", "cap_applies"), True),
    (("stencil", "tilt_controls", "stationary", "nonzero_displacements"), 4),
    (("stencil", "tilt_controls", "tilted_isotropic", "positive_centered_radius"), "3"),
    (("fock", "3", "inverse_basis_stage_evaluations"), 0),
    (("fock", "3", "inverse_history_sha256"), "0"*64),
    (("fock", "2", "roundtrip_sha256"), "0"*64),
]


def alter(value, path, replacement):
    for part in path[:-1]:
        value = value[part]
    value[path[-1]] = replacement


@pytest.mark.parametrize("path,replacement", MUTATIONS)
def test_semantic_forgery_rejected(evidence, path, replacement):
    bad = copy.deepcopy(evidence)
    alter(bad, path, replacement)
    assert bad != evidence
    with pytest.raises(ValueError, match="independent reconstruction"):
        check.verify_evidence(bad)


@pytest.mark.parametrize("section", ["words", "spectra", "nodes", "thermal", "fock",
                                     "budget", "finite_delay", "current", "tetra", "stencil"])
def test_missing_catalog_rejected(evidence, section):
    bad = copy.deepcopy(evidence)
    del bad[section]
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


def test_coordinated_bosonic_permutation_rejected(evidence):
    bad = copy.deepcopy(evidence)
    for sites in (2, 3):
        bad["fock"][str(sites)] = model.fock_program(sites, retain_sign=False)
        assert bad["fock"][str(sites)]["one_particle"] == evidence["fock"][str(sites)]["one_particle"]
    assert bad != evidence  # All metadata and digests were regenerated by the wrong physics.
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


def test_inverse_program_rejects_forward_flight_substitution(monkeypatch):
    original = model.flight_basis
    def wrong_inverse(state, sites, retain_sign=True, direction=1):
        return original(state, sites, retain_sign=retain_sign, direction=1)
    monkeypatch.setattr(model, "flight_basis", wrong_inverse)
    with pytest.raises(ValueError, match="executed inverse program"):
        model.fock_program(3)


def test_all_basis_states_execute_the_complete_reverse_program(evidence):
    for case in evidence["fock"].values():
        assert case["inverse_basis_stage_evaluations"] == case["basis_stage_evaluations"]
        assert case["inverse_history_sha256"] != case["full_history_sha256"]
        identity = check.encoded(check.eye(case["fock_dimension"]))
        assert case["roundtrip_sha256"] == check.digest(identity)


def test_phase_conjugation_preserves_probabilities_but_is_rejected(evidence, monkeypatch):
    bad = copy.deepcopy(evidence)
    monkeypatch.setattr(model, "I", -model.I)
    bad["fock"]["3"] = model.fock_program(3)
    before, after = evidence["fock"]["3"], bad["fock"]["3"]
    for row, changed in zip(before["one_particle"], after["one_particle"]):
        for entry, conjugated in zip(row, changed):
            assert sum(check.F(x)**2 for x in entry) == sum(check.F(x)**2 for x in conjugated)
    assert before["one_particle"] != after["one_particle"]
    assert before["full_fock_sha256"] != after["full_fock_sha256"]
    assert before["full_history_sha256"] != after["full_history_sha256"]
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


def test_coordinated_retiming_rejected(evidence, monkeypatch):
    original_digest = model.digest
    def retimed_digest(history):
        changed = copy.deepcopy(history)
        for event in changed:
            for sample in event["positions"]:
                sample[0] = str(check.F(sample[0])/3)
        return original_digest(changed)
    monkeypatch.setattr(model, "digest", retimed_digest)
    bad = copy.deepcopy(evidence)
    for key, old in evidence["words"].items():
        changed = model.native_word(tuple(old["order"]))
        changed["duration"], changed["effective_speed"] = "1", "1"
        assert changed["kernel"] == old["kernel"]
        assert changed["history_sha256"] != old["history_sha256"]
        bad["words"][key] = changed
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


def test_coordinated_species_filter_rejected(evidence):
    bad = copy.deepcopy(evidence)
    bad["nodes"] = bad["nodes"][:1]
    for catalog in bad["spectra"].values():
        catalog["zero_points"] = [[0, 0, 0]]
    with mp.workdps(75):
        for catalog in bad["thermal"].values():
            catalog["zero_momenta"] = 1
            for beta, values in catalog["cases"].items():
                values[:] = [check.decimal(mp.mpf(x)/8) for x in values]
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


@pytest.mark.parametrize("stages", [
    [["1", ["3", "0", "0"], ["1", "0", "0"]]],
    [["1", ["1", "0", "0"], ["3", "0", "0"]]],
    [["-1", ["1", "0", "0"], ["1", "0", "0"]]],
    [["2", ["1", "0", "0"], ["1", "0", "0"]]],
    [[True, ["1", "0", "0"], ["1", "0", "0"]]],
    [["1", ["1", "1", "0"], ["1", "0", "0"]]],
])
def test_invalid_positive_velocity_resolution_rejected(stages):
    with pytest.raises(ValueError):
        check.validate_resolution(stages)


def test_exact_budget_boundary(evidence):
    for case in evidence["budget"].values():
        matrix, elapsed = check.validate_resolution(case["stages"])
        assert [[str(x) for x in row] for row in matrix] == case["velocity"]
        assert str(elapsed) == case["charged_flight_time"]
    assert check.validate_resolution([]) == ([[check.F(0)]*3 for _ in range(3)], 0)


@pytest.mark.parametrize("index", [0, 4, 8, 14, 17, 25, 28, 34, 42, 45, 49, 50, 54])
def test_optimized_cli_rejects_semantic_forgery(evidence, tmp_path, index):
    packet = verify.strict_load(verify.HERE/"receipt.json")
    path, replacement = MUTATIONS[index]
    alter(packet["evidence"], path, replacement)
    bad = tmp_path/"forgery.json"
    bad.write_text(json.dumps(packet), encoding="utf-8")
    result = subprocess.run([sys.executable, "-O", str(verify.HERE/"verify.py"), str(bad)],
                            capture_output=True, text=True)
    assert result.returncode != 0
    assert "independent reconstruction" in result.stderr


@pytest.mark.parametrize("raw", ['{"x":1,"x":2}', '{"x":NaN}', '{"x":Infinity}'])
def test_strict_json(raw, tmp_path):
    path = tmp_path/"bad.json"
    path.write_text(raw, encoding="utf-8")
    with pytest.raises(ValueError):
        verify.strict_load(path)


@pytest.mark.parametrize("value", [{}, [], {"schema": "oph-m1-quantum-transport-v1"}])
def test_empty_envelope_rejected(value, tmp_path):
    path = tmp_path/"bad.json"
    path.write_text(json.dumps(value), encoding="utf-8")
    with pytest.raises(ValueError):
        verify.verify(path)


def test_verifier_without_producer_or_sympy():
    script = ("import sys; sys.path.insert(0, sys.argv[1]); "
              "sys.modules['sympy']=None; sys.modules['m1_quantum_transport.model']=None; "
              "sys.modules['m1_quantum_transport.tetra_model']=None; "
              "sys.modules['m1_quantum_transport.stencil_model']=None; "
              "from m1_quantum_transport.verify import verify; verify()")
    subprocess.run([sys.executable, "-O", "-c", script, str(verify.ROOT/"code")], check=True)


def test_source_and_parent_custody(tmp_path, monkeypatch):
    packet = verify.strict_load(verify.HERE/"receipt.json")
    monkeypatch.setattr(verify, "pins", lambda: {**packet["sources"], "unexpected": "0"*64})
    with pytest.raises(ValueError, match="source pins"):
        verify.verify()


def test_parent_claims_are_unique_and_required(tmp_path):
    registry = verify.strict_load(verify.ROOT/"claims/claim_registry.yaml")
    parent = next(r for r in registry["claims"] if r["claim_id"] == verify.PARENTS[0])
    for rows in ([r for r in registry["claims"] if r != parent], registry["claims"]+[parent]):
        path = tmp_path/"claims.json"
        path.write_text(json.dumps({"claims": rows}), encoding="utf-8")
        with pytest.raises(ValueError, match="exactly once"):
            verify.parent_claims(path)


def test_every_pinned_source_triggers_ci_and_axiom_audit():
    import fnmatch
    import yaml
    workflow = yaml.safe_load((verify.ROOT/".github/workflows/m1-quantum-transport.yml").read_text())
    triggers = workflow.get("on", workflow.get(True))
    patterns = triggers["pull_request"]["paths"]
    for path in [*verify.SOURCE_FILES, "claims/claim_registry.yaml"]:
        assert any(fnmatch.fnmatchcase(path, pattern) for pattern in patterns), path
    assert "Geometry.M1QuantumTransportAxiomAudit" in (verify.ROOT/".github/workflows/lean-ci.yml").read_text()


def test_all_cone_dynamics_against_explicit_error_bound():
    with mp.workdps(45):
        pauli = (mp.matrix([[0, 1], [1, 0]]), mp.matrix([[0, -1j], [1j, 0]]),
                 mp.matrix([[1, 0], [0, -1]]))
        for node, q, k in itertools.product(check.nodes(), (32, 128),
                                           ((1, 2, 3), (-2, 1, 0), (0, 0, 1))):
            a, time = mp.mpf(1)/q, mp.mpf(7)/10
            tick = 3*a
            steps = int(time/tick)
            actual = mp.eye(2)
            for axis in range(3):
                theta = mp.pi*node["index"][axis]/2+a*k[axis]
                actual = (mp.cos(theta)*mp.eye(2)-mp.j*mp.sin(theta)*pauli[axis])*actual
            generator = sum((k[i]*int(node["derivative"][i][i])*pauli[i] for i in range(3)), mp.zeros(2))
            normk = mp.sqrt(sum(x*x for x in k))
            target = mp.cos(time*normk/3)*mp.eye(2)-mp.j*mp.sin(time*normk/3)*generator/normk
            difference = actual**steps-target
            # Frobenius/sqrt(2) equals the operator norm for the difference of SU(2) matrices.
            error = mp.sqrt(sum(abs(x)**2 for x in difference)/2)
            assert error <= (2*time/3)*a*normk**2+a*normk


def test_global_coercivity_on_complete_shifted_grids():
    with mp.workdps(40):
        zeros = [[mp.pi*i/2 for i in node["index"]] for node in check.nodes()]
        for raw in itertools.product(range(7), repeat=3):
            theta = [2*mp.pi*(mp.mpf(i)+mp.mpf(1)/7)/7 for i in raw]
            scalar = mp.fprod(mp.cos(x) for x in theta)+mp.fprod(mp.sin(x) for x in theta)
            epsilon = mp.acos(scalar)
            def distance(zero):
                return mp.sqrt(sum(((x-y+mp.pi) % (2*mp.pi)-mp.pi)**2 for x, y in zip(theta, zero)))
            assert epsilon >= min(map(distance, zeros))/(8*mp.sqrt(3))


def test_conjugated_tetrahedral_process_rejected(evidence, monkeypatch):
    from m1_quantum_transport import tetra_model
    monkeypatch.setattr(tetra_model, "COIN", tetra_model.COIN.conjugate())
    bad = copy.deepcopy(evidence)
    bad["tetra"] = tetra_model.candidate()
    assert bad["tetra"]["thermal"] == evidence["tetra"]["thermal"]
    assert bad["tetra"]["bands"] != evidence["tetra"]["bands"]
    assert bad["tetra"]["fock"] != evidence["tetra"]["fock"]
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


def test_coordinated_tetrahedral_high_band_filter_rejected(evidence):
    bad = copy.deepcopy(evidence)
    with mp.workdps(75):
        for qtext, catalog in bad["tetra"]["thermal"].items():
            q = int(qtext)
            catalog["modes"] = 2*q**3
            epsilon = [mp.asin(mp.sqrt(sum(mp.sinpi(mp.mpf(2)*x/q)**2 for x in k)/3))
                       for k in itertools.product(range(q), repeat=3)]
            energies = [e*q/mp.sqrt(3) for e in epsilon]
            for beta in (1, 2):
                z = mp.fsum(2*mp.log1p(mp.exp(-beta*e)) for e in energies)
                energy = mp.fsum(2*e/(1+mp.exp(beta*e)) for e in energies)
                catalog["cases"][str(beta)] = [check.decimal(x) for x in (z, energy, z+beta*energy)]
    with pytest.raises(ValueError):
        check.verify_evidence(bad)


def test_general_stencil_bound_and_minimal_design(evidence):
    from m1_quantum_transport.stencil_check import validate_isotropic_support, validate_design
    tetra = evidence["stencil"]["polytopes"]["tetrahedron"]["points"]
    cube = evidence["stencil"]["polytopes"]["cube"]["points"]
    assert validate_isotropic_support(tetra, "3", "1/9", "1")["geometric_ratio_squared"] == "1/9"
    assert validate_isotropic_support(cube, "3", "1/3", "1")["geometric_ratio_squared"] == "1/3"
    assert validate_isotropic_support(cube, "9", "1/9", "1")["inradius_squared"] == "1"
    for name in ("tetrahedron", "cube", "octahedron"):
        points = evidence["stencil"]["polytopes"][name]["points"]
        assert validate_design(points, [str(check.F(1, len(points)))]*len(points))


def test_positive_radius_scope_retains_valid_degenerate_stencils(evidence):
    controls = evidence["stencil"]["tilt_controls"]
    for name, count in (("stationary", 0), ("translation", 1)):
        case = controls[name]
        assert case["nonzero_displacements"] == count
        assert case["positive_centered_radius"] is None
        assert case["cap_applies"] is False
        assert count < 2  # A clamped zero radius would falsely exclude these unitaries.
    assert controls["translation"]["tilt"] == ["1", "0", "0"]
    assert controls["translation"]["velocity"] == [["0"]*3 for _ in range(3)]
    positive = controls["tilted_isotropic"]
    assert positive["positive_centered_radius"] == "2" and positive["cap_applies"]
    from m1_quantum_transport.stencil_check import validate_isotropic_support
    support = [[1+3*x, 3*y, 3*z] for x, y, z in itertools.product((-1, 1), repeat=3)]
    assert validate_isotropic_support(support, "1", "4", "34")["inradius_squared"] == "4"


def test_two_channels_reused_across_six_saturating_velocity_outcomes(evidence):
    from m1_quantum_transport.stencil_check import validate_design
    directions, weights = [], []
    for duration, spatial, spin in evidence["budget"]["isotropic"]["stages"]:
        assert spatial == spin
        for sign in (-1, 1):
            directions.append([sign*int(x) for x in spatial])
            weights.append(str(check.F(duration)/2))
    assert len(directions) == 6 and validate_design(directions, weights)
    for _, coefficient in evidence["words"]["012"]["kernel"]:
        assert len(coefficient) == 2 and all(len(row) == 2 for row in coefficient)
    assert evidence["budget"]["isotropic"]["velocity"] == [
        ["1/3", "0", "0"], ["0", "1/3", "0"], ["0", "0", "1/3"]]


@pytest.mark.parametrize("case", ["luminal", "undercharged", "negative", "flat", "duplicate", "zero_bonus"])
def test_trash_stencil_rejected(evidence, case):
    from m1_quantum_transport.stencil_check import validate_isotropic_support
    points = copy.deepcopy(evidence["stencil"]["polytopes"]["cube"]["points"])
    time, field, native = "3", "1", "1"
    if case == "undercharged":
        time, field = "1", "1/9"
    elif case == "negative":
        time = "-3"
    elif case == "flat":
        points = [[p[0], p[1], 0] for p in points]
    elif case == "duplicate":
        points = [points[0]]*100
    elif case == "zero_bonus":
        points += [[0, 0, 0]]*100
    with pytest.raises(ValueError):
        validate_isotropic_support(points, time, field, native)


@pytest.mark.parametrize("case", ["three", "unequal", "subnormalized", "duplicate", "anisotropic"])
def test_false_saturating_design_rejected(evidence, case):
    from m1_quantum_transport.stencil_check import validate_design
    points = copy.deepcopy(evidence["stencil"]["polytopes"]["tetrahedron"]["points"])
    weights = ["1/4"]*4
    if case == "three":
        points, weights = points[:3], ["1/3"]*3
    elif case == "unequal":
        weights = ["1/2", "1/6", "1/6", "1/6"]
    elif case == "subnormalized":
        weights = ["1/5"]*4
    elif case == "duplicate":
        points[0] = points[1]
    elif case == "anisotropic":
        points = [[p[0], p[1], 2*p[2]] for p in points]
    with pytest.raises(ValueError):
        validate_design(points, weights)


def test_tetrahedral_all_channel_dynamics_and_native_tick():
    with mp.workdps(40):
        coin = mp.matrix([[0, 1, 1, 1], [1, 0, mp.j, -mp.j],
                          [1, -mp.j, 0, mp.j], [1, mp.j, -mp.j, 0]])/mp.sqrt(3)
        points = [(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)]
        x = []
        for i in range(3):
            b = mp.diag([point[i] for point in points])
            x.append(mp.sqrt(3)*(b+coin*b*coin)/2)
        for node, q, k in itertools.product(itertools.product((0, 1), repeat=3), (32, 128),
                                           ((1, 2, 3), (-2, 1, 0), (0, 0, 1))):
            a, time = mp.mpf(1)/q, mp.mpf(7)/10
            tick, eta = mp.sqrt(3)*a, (-1)**sum(node)
            steps = int(time/tick)
            u = mp.diag([mp.exp(-mp.j*a*sum(p[i]*k[i] for i in range(3))) for p in points])*eta*coin
            generator = sum((k[i]*x[i] for i in range(3)), mp.zeros(4))
            normk = mp.sqrt(sum(v*v for v in k))
            slow = mp.cos(time*normk/3)*mp.eye(4)-mp.j*mp.sin(time*normk/3)*generator/normk
            target = (eta*coin)**steps*slow
            error = max(mp.svd(u**steps-target, compute_uv=False))
            assert error <= (mp.sqrt(3)*time/2)*a*normk**2+(4/mp.sqrt(3))*a*normk
        # A two-tick alias must not erase the high-band phase on the original clock.
        assert max(mp.svd(coin-mp.eye(4), compute_uv=False)) > mp.mpf('1.999')
