import Geometry.SourceTemporalGuard

/-!
# Complete record grammar and native checkpoint viability

A supplied public record map generates its entire algebra of interpreted
tests. Equality of its primitive coordinates is a complete agreement
grammar, including nonlinear tests. Native continuation viability is then
derived, rather than assumed as a successful schedule. This is a theorem
about the specified interface, not a selection of that interface by A1.
-/

set_option autoImplicit false

namespace OPH.SourceCheckpointMeaning
noncomputable section
open OPH.SourceTemporalGuard OPH.SourceTemporalTomography

variable {X R O V P : Type*} [DecidableEq P]

def Determines (observation : X → O) (record : X → R) : Prop :=
  ∀ x y, observation x = observation y → record x = record y

/-- Every interpreted test generated by the public record map agrees iff
the record itself agrees. Boolean equality tests suffice. -/
theorem complete_test_grammar (observation : X → O) (record : X → R) :
    Determines observation record ↔
      ∀ test : R → Prop, ∀ x y, observation x = observation y →
        (test (record x) ↔ test (record y)) := by
  constructor
  · intro h test x y he
    rw [h x y he]
  · intro h x y he
    exact (h (fun r => record x = r) x y he).mp rfl

theorem coordinates_complete {I A : Type*} (observation : X → O)
    (record : X → I → A) :
    Determines observation record ↔ ∀ i, Determines observation (fun x => record x i) := by
  constructor
  · intro h i x y he
    exact congrFun (h x y he) i
  · intro h x y he
    exact funext (fun i => h i x y he)

theorem interpretation_closed (observation : X → O) (record : X → R)
    (h : Determines observation record) (test : R → V) :
    Determines observation (test ∘ record) := by
  intro x y he
  exact congrArg test (h x y he)

/-- An injective re-encoding changes no required observation. Selection
depends on public distinctions, not their coordinate names. -/
theorem reencode_iff (observation : X → O) (record : X → R) (encode : R → V)
    (hi : Function.Injective encode) :
    Determines observation (encode ∘ record) ↔ Determines observation record := by
  constructor
  · intro h x y he
    exact hi (h x y he)
  · intro h
    exact interpretation_closed observation record h encode

def Viable (meaning : X → R) (c : Checkpoint X P) : Prop :=
  ∀ x y, c.record x = c.record y → c.state x = c.state y → meaning x = meaning y

def Published (meaning : X → R) (c : Checkpoint X P) : Prop :=
  Determines c.record meaning

theorem published_viable (meaning : X → R) (c : Checkpoint X P)
    (h : Published meaning c) : Viable meaning c := by
  intro x y hr _
  exact h x y hr

theorem publication_extends (meaning : X → R) (root : P)
    (c : Checkpoint X P) (es : List (P × P)) (h : Published meaning c) :
    Published meaning (run root es c) := by
  intro x y he
  exact h x y (run_record_extends root es c x y he)

/-- Every successful continuation excludes irreversible loss in its prefix. -/
theorem publication_requires_viability (meaning : X → R) (root : P)
    (c : Checkpoint X P) (es : List (P × P))
    (h : Published meaning (run root es c)) : Viable meaning c := by
  intro x y hr hs
  exact h x y (run_equal_data root es c x y hr hs)

/-- The topology-derived word completes any viable meaning, including
checkpoints that discard irrelevant preparation details. -/
theorem plan_publishes_iff (meaning : X → R) {root : P}
    (plan : Plan root {root}) (c : Checkpoint X P) (hr : HasRoot root c) :
    Published meaning (run root (lower plan) c) ↔ Viable meaning c := by
  constructor
  · exact publication_requires_viability meaning root c (lower plan)
  · intro h x y he
    have ht := run_trace root (lower plan) c hr x y he
    apply h x y (run_record_extends root (lower plan) c x y he)
    apply completion_injective plan
    exact congrArg₂ List.cons (trace_head root (lower plan) _ _ ht)
      (trace_plan_samples plan _ _ ht)

/-- An exact necessary and sufficient continuation rule, with a finite
native work bound. No schedule is supplied to the theorem. -/
theorem connected_viability_iff [Fintype P] (G : SimpleGraph P)
    (hc : G.Connected) (meaning : X → R) (root : P)
    (c : Checkpoint X P) (hr : HasRoot root c) :
    Viable meaning c ↔ ∃ es : List (P × P),
      SourceTemporalConnected.Supported G es ∧
      2 * es.length + Fintype.card P ≤ Fintype.card P ^ 2 ∧
      Published meaning (run root es c) := by
  obtain ⟨plan, hs, _⟩ := SourceTemporalConnected.connected_native_completion G hc root
  constructor
  · intro h
    refine ⟨lower plan, hs, ?_, (plan_publishes_iff meaning plan c hr).mpr h⟩
    simpa only [lower_length] using (complete_work_bound plan).2
  · rintro ⟨es, _, _, h⟩
    exact publication_requires_viability meaning root c es h

/-- Deleting even one distinguishing pair admits an observational collision.
This witness defeats every linear or nonlinear interpreted decoder. -/
theorem missing_pair_blocks_decoder (observation : X → O) (meaning : X → R)
    (h : ¬ Determines observation meaning) :
    ∃ x y, observation x = observation y ∧ meaning x ≠ meaning y := by
  simpa [Determines] using h

end
end OPH.SourceCheckpointMeaning
