import Geometry.SourceReusableBusAxiomAudit
import Geometry.SourceReadSelection

/-! Reuse the transitive standard-axiom gate, including its sorry/compiler
negative controls. The complete imported trust chain is pinned by the receipt. -/

audit_reusable_bus_axioms OPH.SourceReadSelection.full_support_criterion
audit_reusable_bus_axioms OPH.SourceReadSelection.selected_support_criterion
audit_reusable_bus_axioms OPH.SourceReadSelection.liftWord_injective
audit_reusable_bus_axioms OPH.SourceReadSelection.liftWord_range
audit_reusable_bus_axioms OPH.SourceReadSelection.selected_subalphabet_mass
audit_reusable_bus_axioms OPH.SourceReadSelection.two_input_error_bound
audit_reusable_bus_axioms OPH.SourceReadSelection.mean_outside_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.run_outside_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.local_read_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.local_transcript_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.cut_word_not_both_correct
audit_reusable_bus_axioms OPH.SourceReadSelection.cut_transcript_not_both_correct
audit_reusable_bus_axioms OPH.SourceReadSelection.correct_pair_requires_crossing
audit_reusable_bus_axioms OPH.SourceReadSelection.selected_remote_read_obstruction
