import Geometry.SourceConstrainedSelection

/-!
# Reads generated by disjoint source repairs

The registered simulator matches every port slot exactly once. These results
classify the ideal real pair means on that matching. IEEE arithmetic, the
no-op threshold, normalized preparation rank, and the matrix-exponential
enclosure are treated separately in the accompanying analytic derivation.
-/

set_option autoImplicit false

namespace OPH.SourceOperationReads
noncomputable section

/-- Apply the mean on the selected pairs of an involutive matching. -/
def project {X : Type*} (mate : X → X) (selected : X → Bool)
    (state : X → ℝ) (i : X) : ℝ :=
  if selected i then (state i + state (mate i))/2 else state i

/-- Membership in a set of complete pairs is constant across each pair. -/
def Paired {X : Type*} (mate : X → X) (selected : X → Bool) : Prop :=
  ∀ i, selected (mate i) = selected i

/-- The union of selected pairs is a selected-pair family. -/
theorem paired_union {X : Type*} (mate : X → X) (a b : X → Bool)
    (ha : Paired mate a) (hb : Paired mate b) :
    Paired mate (fun i => a i || b i) := by
  intro i
  simp [ha i, hb i]

/-- Disjoint pair means compose by union, including repeated operations. -/
theorem project_union {X : Type*} (mate : X → X)
    (hm : Function.Involutive mate) (a b : X → Bool)
    (hb : Paired mate b) (state : X → ℝ) :
    project mate a (project mate b state) =
      project mate (fun i => a i || b i) state := by
  funext i
  cases h₁ : a i <;> cases h₂ : b i <;>
    simp [project, h₁, h₂, hb i, hm i]
  all_goals ring

/-- Every selected matching projection is idempotent. -/
theorem project_idempotent {X : Type*} (mate : X → X)
    (hm : Function.Involutive mate) (a : X → Bool)
    (ha : Paired mate a) (state : X → ℝ) :
    project mate a (project mate a state) = project mate a state := by
  simpa using project_union mate hm a a ha state

/-- Every two selected matching projections commute. -/
theorem project_commute {X : Type*} (mate : X → X)
    (hm : Function.Involutive mate) (a b : X → Bool)
    (ha : Paired mate a) (hb : Paired mate b) (state : X → ℝ) :
    project mate a (project mate b state) = project mate b (project mate a state) := by
  rw [project_union mate hm a b hb, project_union mate hm b a ha]
  simp [Bool.or_comm]

/-- The set of pairs visited by a finite operation word. -/
def visited {X : Type*} : List (X → Bool) → X → Bool
  | [] => fun _ => false
  | a :: rest => fun i => a i || visited rest i

/-- Compose the finite operation word. -/
def execute {X : Type*} (mate : X → X) : List (X → Bool) → (X → ℝ) → X → ℝ
  | [] => id
  | a :: rest => fun state => project mate a (execute mate rest state)

/-- A union over a finite operation word contains complete pairs. -/
theorem visited_paired {X : Type*} (mate : X → X) (word : List (X → Bool))
    (h : ∀ a ∈ word, Paired mate a) : Paired mate (visited word) := by
  induction word with
  | nil => intro i; rfl
  | cons a rest ih =>
    exact paired_union mate a (visited rest) (h a (by simp))
      (ih (fun b hb => h b (by simp [hb])))

/-- The complete finite transition depends only on the visited-pair set. -/
theorem execute_eq_project {X : Type*} (mate : X → X)
    (hm : Function.Involutive mate) (word : List (X → Bool))
    (h : ∀ a ∈ word, Paired mate a) (state : X → ℝ) :
    execute mate word state = project mate (visited word) state := by
  induction word with
  | nil => rfl
  | cons a rest ih =>
    have hr : ∀ b ∈ rest, Paired mate b := fun b hb => h b (by simp [hb])
    simp only [execute, visited, ih hr]
    exact project_union mate hm a (visited rest) (visited_paired mate rest hr) state

/-- A receiver coordinate depends only on its own initial pair. -/
theorem pair_dependency {X : Type*} (mate : X → X) (a : X → Bool)
    (x y : X → ℝ) (i : X) (hi : x i = y i) (hm : x (mate i) = y (mate i)) :
    project mate a x i = project mate a y i := by
  simp [project, hi, hm]

/-- The dependency statement holds for every word of permitted means. -/
theorem word_dependency {X : Type*} (mate : X → X) (hm : Function.Involutive mate)
    (word : List (X → Bool)) (h : ∀ a ∈ word, Paired mate a)
    (x y : X → ℝ) (i : X) (hi : x i = y i) (hp : x (mate i) = y (mate i)) :
    execute mate word x i = execute mate word y i := by
  rw [execute_eq_project mate hm word h, execute_eq_project mate hm word h]
  exact pair_dependency mate (visited word) x y i hi hp

/-- An exact retained initial value and a committed mean recover its partner. -/
theorem recover_partner (localValue remoteValue : ℝ) :
    2*((localValue+remoteValue)/2)-localValue = remoteValue := by ring

/-- Two hidden normalized coordinates can change without changing their sum. -/
theorem balanced_hidden_change (a b delta : ℝ) :
    (a+delta)+(b-delta) = a+b := by ring

/-- Equal observed payloads cannot determine two different required values. -/
theorem no_decoder {X O V : Type*} (observe : X → O) (required : X → V)
    (x y : X) (ho : observe x = observe y) (hv : required x ≠ required y) :
    ¬ ∃ decode : O → V, ∀ state, decode (observe state) = required state := by
  rintro ⟨decode, hd⟩
  apply hv
  rw [← hd x, ho, hd y]

/-- The two balanced hidden values used by the exact normalized controls differ. -/
theorem hidden_values : (1/12:ℚ)+1/48 = 5/48 ∧
    (1/12:ℚ)-1/48 = 1/16 ∧ (5/48:ℚ) ≠ 1/16 := by norm_num

/-- Phase-sensitive output probabilities differ although input intensities agree. -/
theorem phase_gap_polynomial (a b c d : ℝ) :
    ((a-d)^2+(b+c)^2)/2 - ((a+d)^2+(b-c)^2)/2 = 2*(b*c-a*d) := by ring

/-- The declared small binary step has a strictly positive analytic phase bound. -/
theorem native_phase_bound :
    0 < 2*(1/131072:ℚ)-400*(1/131072:ℚ)^2 := by norm_num

/-- An input stabilizer that moves the output rules out equivariance. -/
theorem stabilizer_obstruction {X Y : Type*} (inputAction : X → X)
    (outputAction : Y → Y) (select : X → Y) (x : X)
    (hx : inputAction x = x) (hy : outputAction (select x) ≠ select x) :
    ¬ ∀ z, select (inputAction z) = outputAction (select z) := by
  intro h
  apply hy
  simpa [hx] using (h x).symm

end
end OPH.SourceOperationReads
