import Geometry.SourceReusableBusAxiomAudit
import Geometry.SourceOperationReads
import Geometry.SourceRepairInstrument

/-! Standard-axiom audit for the disjoint source-operation and read theorems. -/

audit_reusable_bus_axioms OPH.SourceOperationReads.paired_union
audit_reusable_bus_axioms OPH.SourceOperationReads.project_union
audit_reusable_bus_axioms OPH.SourceOperationReads.project_idempotent
audit_reusable_bus_axioms OPH.SourceOperationReads.project_commute
audit_reusable_bus_axioms OPH.SourceOperationReads.visited_paired
audit_reusable_bus_axioms OPH.SourceOperationReads.execute_eq_project
audit_reusable_bus_axioms OPH.SourceOperationReads.pair_dependency
audit_reusable_bus_axioms OPH.SourceOperationReads.word_dependency
audit_reusable_bus_axioms OPH.SourceOperationReads.recover_partner
audit_reusable_bus_axioms OPH.SourceOperationReads.balanced_hidden_change
audit_reusable_bus_axioms OPH.SourceOperationReads.no_decoder
audit_reusable_bus_axioms OPH.SourceOperationReads.hidden_values
audit_reusable_bus_axioms OPH.SourceOperationReads.phase_gap_polynomial
audit_reusable_bus_axioms OPH.SourceOperationReads.native_phase_bound
audit_reusable_bus_axioms OPH.SourceOperationReads.stabilizer_obstruction
audit_reusable_bus_axioms OPH.SourceRepairInstrument.relabel_cptp
audit_reusable_bus_axioms OPH.SourceRepairInstrument.twirl_cptp
audit_reusable_bus_axioms OPH.SourceRepairInstrument.twirl_diagonal
audit_reusable_bus_axioms OPH.SourceRepairInstrument.twirl_idempotent
audit_reusable_bus_axioms OPH.SourceRepairInstrument.dephase_kraus
audit_reusable_bus_axioms OPH.SourceRepairInstrument.dephase_cptp
audit_reusable_bus_axioms OPH.SourceRepairInstrument.measured_twirl_cptp
audit_reusable_bus_axioms OPH.SourceRepairInstrument.dephase_diagonal
audit_reusable_bus_axioms OPH.SourceRepairInstrument.ensemble_identity
audit_reusable_bus_axioms OPH.SourceRepairInstrument.threshold_nonaffine
audit_reusable_bus_axioms OPH.SourceRepairInstrument.local_normalization_change
audit_reusable_bus_axioms OPH.SourceRepairInstrument.phase_lift_gap
audit_reusable_bus_axioms OPH.SourceRepairInstrument.coordinate_sandwich
audit_reusable_bus_axioms OPH.SourceRepairInstrument.coordinate_commutator

audit_reusable_bus_axioms OPH.SourceRepairInstrument.relabel_recovery
audit_reusable_bus_axioms OPH.SourceRepairInstrument.retained_branch_recovery
audit_reusable_bus_axioms OPH.SourceRepairInstrument.deterministic_pair_recovery
