import Geometry.SourceBankTrace

/-! Generated by `python -m source_native_programs.lean_control`.
Finite logical-stream, observed-scale, native-work and signed-output
correspondence with controls.json. Scalar-port embedding is not asserted. -/

set_option autoImplicit false
set_option maxRecDepth 4096

namespace OPH.SourceBankControl
open OPH.SourceBankMachine OPH.SourceBankTrace

def menus : List (Layer 2) := [![[0,1],[0,0]],![[1,0],[]],![[0,1,0],[1]]]
def rd (i : ℕ) : ℕ := ([8,9,9,12] : List ℕ)[i-4]?.getD 0
def wd (i : ℕ) : ℕ := ([9,8,7,14] : List ℕ)[i-4]?.getD 0
def ops : List Op := program 2 rd wd false menus
def rows : List Row := [
  (.start,[(4,0),(5,0),(0,1),(2,1)],267),
  (.transfer 4 3 8,[(4,1),(5,0),(0,1),(2,1),(3,8)],56072),
  (.add,[(4,1),(5,0),(0,10),(2,1)],29),
  (.retire,[(4,1),(5,0),(0,10),(2,1)],4),
  (.transfer 5 3 9,[(4,1),(5,1),(0,10),(2,1),(3,9)],84498),
  (.add,[(4,1),(5,1),(0,11),(2,1)],5),
  (.retire,[(4,1),(5,1),(0,11),(2,1)],4),
  (.transfer 0 6 7,[(4,1),(5,1),(6,18),(0,12),(2,1)],34863),
  (.start,[(4,1),(5,1),(6,18),(0,2),(2,2)],267),
  (.transfer 4 3 8,[(4,2),(5,1),(6,18),(0,2),(2,2),(3,9)],56072),
  (.add,[(4,2),(5,1),(6,18),(0,11),(2,2)],29),
  (.retire,[(4,2),(5,1),(6,18),(0,11),(2,2)],4),
  (.transfer 4 3 8,[(4,3),(5,1),(6,18),(0,11),(2,2),(3,10)],56072),
  (.add,[(4,3),(5,1),(6,18),(0,12),(2,2)],5),
  (.retire,[(4,3),(5,1),(6,18),(0,12),(2,2)],4),
  (.transfer 0 7 14,[(4,3),(5,1),(6,18),(7,26),(0,13),(2,2)],371829),
  (.start,[(4,3),(5,1),(6,18),(7,26),(0,3),(2,3)],267),
  (.transfer 7 3 12,[(4,3),(5,1),(6,18),(7,27),(0,3),(2,3),(3,38)],223632),
  (.add,[(4,3),(5,1),(6,18),(7,27),(0,40),(2,3)],113),
  (.retire,[(4,3),(5,1),(6,18),(7,27),(0,40),(2,3)],4),
  (.transfer 6 3 9,[(4,3),(5,1),(6,19),(7,27),(0,40),(2,3),(3,27)],84498),
  (.add,[(4,3),(5,1),(6,19),(7,27),(0,41),(2,3)],41),
  (.retire,[(4,3),(5,1),(6,19),(7,27),(0,41),(2,3)],4),
  (.transfer 0 4 9,[(4,50),(5,1),(6,19),(7,27),(0,42),(2,3)],84499),
  (.start,[(4,50),(5,1),(6,19),(7,27),(0,4),(2,4)],267),
  (.transfer 0 5 8,[(4,50),(5,12),(6,19),(7,27),(0,5),(2,4)],56073),
  (.start,[(4,50),(5,12),(6,19),(7,27),(0,5),(2,5)],267),
  (.transfer 4 3 8,[(4,51),(5,12),(6,19),(7,27),(0,5),(2,5),(3,58)],56072),
  (.add,[(4,51),(5,12),(6,19),(7,27),(0,60),(2,5)],167),
  (.retire,[(4,51),(5,12),(6,19),(7,27),(0,60),(2,5)],4),
  (.transfer 5 3 9,[(4,51),(5,13),(6,19),(7,27),(0,60),(2,5),(3,21)],84498),
  (.add,[(4,51),(5,13),(6,19),(7,27),(0,61),(2,5)],119),
  (.retire,[(4,51),(5,13),(6,19),(7,27),(0,61),(2,5)],4),
  (.transfer 4 3 8,[(4,52),(5,13),(6,19),(7,27),(0,61),(2,5),(3,59)],56072),
  (.add,[(4,52),(5,13),(6,19),(7,27),(0,62),(2,5)],8),
  (.retire,[(4,52),(5,13),(6,19),(7,27),(0,62),(2,5)],4),
  (.transfer 0 6 7,[(4,52),(5,13),(6,69),(7,27),(0,63),(2,5)],34863),
  (.start,[(4,52),(5,13),(6,69),(7,27),(0,6),(2,6)],267),
  (.transfer 5 3 9,[(4,52),(5,14),(6,69),(7,27),(0,6),(2,6),(3,22)],84498),
  (.add,[(4,52),(5,14),(6,69),(7,27),(0,24),(2,6)],56),
  (.retire,[(4,52),(5,14),(6,69),(7,27),(0,24),(2,6)],4),
  (.transfer 0 7 14,[(4,52),(5,14),(6,69),(7,38),(0,25),(2,6)],371829)
]

theorem captured_trace : checks 88 ops (fun _ => 0) rows = true := by decide

theorem rejects_empty_trace : checks 88 ops (fun _ => 0) [] = false := by decide
theorem rejects_missing_stage : checks 88 ops (fun _ => 0) rows.dropLast = false := by decide
theorem rejects_extra_stage : checks 88 ops (fun _ => 0) (rows ++ rows.take 1) = false := by decide
theorem rejects_wrong_instruction : checks 88 ops (fun _ => 0)
    (rows.modify 0 fun r => (.retire,r.2)) = false := by decide
theorem rejects_undercharged_work : checks 88 ops (fun _ => 0)
    (rows.modify 0 fun r => (r.1,r.2.1,r.2.2-1)) = false := by decide
theorem rejects_wrong_scale : checks 88 ops (fun _ => 0)
    (rows.modify 0 fun r => (r.1,r.2.1.modify 0 (fun p => (p.1,p.2+1)),r.2.2)) = false := by decide

theorem captured_work : work ops 88 (fun _ => 0) = 1798154 := by
  rw [checks_work _ _ _ _ captured_trace]
  decide

def initial (a b : ℤ) : Values := fun i =>
  if i = 2 then 1 else if i = 4 then a else if i = 5 then b else 0

theorem captured_signed_outputs :
    (([-2,0,2] : List ℤ).flatMap fun a => ([-2,0,2] : List ℤ).map fun b =>
      [values ops (initial a b) 6,values ops (initial a b) 7]) =
      [[-8,2],[-4,2],[0,2],[4,2],[8,2],[12,2],[16,2],[20,2],[24,2]] := by decide

end OPH.SourceBankControl
