import Geometry.SourceReusableBusAxiomAudit
import Geometry.SourceOperationReads

/-! Standard-axiom audit for the disjoint source-operation and read theorems. -/

audit_reusable_bus_axioms OPH.SourceOperationReads.paired_union
audit_reusable_bus_axioms OPH.SourceOperationReads.project_union
audit_reusable_bus_axioms OPH.SourceOperationReads.project_idempotent
audit_reusable_bus_axioms OPH.SourceOperationReads.project_commute
audit_reusable_bus_axioms OPH.SourceOperationReads.visited_paired
audit_reusable_bus_axioms OPH.SourceOperationReads.execute_eq_project
audit_reusable_bus_axioms OPH.SourceOperationReads.pair_dependency
audit_reusable_bus_axioms OPH.SourceOperationReads.word_dependency
audit_reusable_bus_axioms OPH.SourceOperationReads.recover_partner
audit_reusable_bus_axioms OPH.SourceOperationReads.balanced_hidden_change
audit_reusable_bus_axioms OPH.SourceOperationReads.no_decoder
audit_reusable_bus_axioms OPH.SourceOperationReads.hidden_values
audit_reusable_bus_axioms OPH.SourceOperationReads.phase_gap_polynomial
audit_reusable_bus_axioms OPH.SourceOperationReads.native_phase_bound
audit_reusable_bus_axioms OPH.SourceOperationReads.stabilizer_obstruction
