import Geometry.SourceReusableBusAxiomAudit
import Geometry.SourceSelectionLocality

audit_reusable_bus_axioms OPH.SourceSelectionLocality.localRun_eq
audit_reusable_bus_axioms OPH.SourceSelectionLocality.whole_transcript_eq
audit_reusable_bus_axioms OPH.SourceSelectionLocality.any_transcript_decoder_eq
audit_reusable_bus_axioms OPH.SourceSelectionLocality.stopping_read_eq
audit_reusable_bus_axioms OPH.SourceSelectionLocality.cannot_read_both
audit_reusable_bus_axioms OPH.SourceSelectionLocality.copyAcross_reads
audit_reusable_bus_axioms OPH.SourceSelectionLocality.population_zero
audit_reusable_bus_axioms OPH.SourceSelectionLocality.population_recurrence
audit_reusable_bus_axioms OPH.SourceSelectionLocality.population_successor_not_cube
audit_reusable_bus_axioms OPH.SourceSelectionLocality.population_not_cube
audit_reusable_bus_axioms OPH.SourceSelectionLocality.decoder_implies_separation
audit_reusable_bus_axioms OPH.SourceSelectionLocality.separation_implies_decoder
audit_reusable_bus_axioms OPH.SourceSelectionLocality.exact_decoder_iff
audit_reusable_bus_axioms OPH.SourceSelectionLocality.collision_excludes_decoder
audit_reusable_bus_axioms OPH.SourceSelectionLocality.separated_channels_compose
