import Geometry.SourceReusableBusAxiomAudit
import Geometry.SourceReadSelection
import Geometry.SourceConstrainedRead
import Geometry.SourceSelectionControls

/-! Reuse the transitive standard-axiom gate, including its sorry/compiler
negative controls. The complete imported trust chain is pinned by the receipt. -/

audit_reusable_bus_axioms OPH.SourceReadSelection.full_support_criterion
audit_reusable_bus_axioms OPH.SourceReadSelection.selected_support_criterion
audit_reusable_bus_axioms OPH.SourceReadSelection.liftWord_injective
audit_reusable_bus_axioms OPH.SourceReadSelection.liftWord_range
audit_reusable_bus_axioms OPH.SourceReadSelection.selected_subalphabet_mass
audit_reusable_bus_axioms OPH.SourceReadSelection.two_input_error_bound
audit_reusable_bus_axioms OPH.SourceReadSelection.mean_outside_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.run_outside_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.local_read_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.local_transcript_eq
audit_reusable_bus_axioms OPH.SourceReadSelection.cut_word_not_both_correct
audit_reusable_bus_axioms OPH.SourceReadSelection.cut_transcript_not_both_correct
audit_reusable_bus_axioms OPH.SourceReadSelection.correct_pair_requires_crossing
audit_reusable_bus_axioms OPH.SourceReadSelection.selected_remote_read_obstruction

audit_reusable_bus_axioms OPH.SourceConstrainedSelection.entropyTerm_mixture_le
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.entropyTerm_zero_mixture
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.potential_mixture_gap
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.exists_small_log
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.potential_minimizer_support
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.klTerm_expansion
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.weightedKL_expansion
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.weightedKL_minimizer_support
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.selected_zero_event_iff
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.weightedKL_nonnegative
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.weightedKL_self
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.weightedKL_zero_iff
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.klTerm_projection_identity
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.weightedKL_projection_identity
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.affine_certificate_unique_minimum
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.positive_readout_zero_of_support
audit_reusable_bus_axioms OPH.SourceConstrainedSelection.selected_zero_readout_iff

audit_reusable_bus_axioms OPH.SourceSelectionControls.word_reference_positive
audit_reusable_bus_axioms OPH.SourceSelectionControls.word_selected_positive
audit_reusable_bus_axioms OPH.SourceSelectionControls.word_selected_constraints
audit_reusable_bus_axioms OPH.SourceSelectionControls.word_selected_correlated
audit_reusable_bus_axioms OPH.SourceSelectionControls.constrained_word_unique_minimum
audit_reusable_bus_axioms OPH.SourceSelectionControls.historyFamily_feasible
audit_reusable_bus_axioms OPH.SourceSelectionControls.historyFeasible_convex
audit_reusable_bus_axioms OPH.SourceSelectionControls.coarseCover_state_determining
audit_reusable_bus_axioms OPH.SourceSelectionControls.history_atom_recovered_with_negative_offset
audit_reusable_bus_axioms OPH.SourceSelectionControls.compatible_faithful_reference
audit_reusable_bus_axioms OPH.SourceSelectionControls.coarse_selected_readout
audit_reusable_bus_axioms OPH.SourceSelectionControls.coarse_cover_unique_minimum
audit_reusable_bus_axioms OPH.SourceSelectionControls.full_selected_feasible
audit_reusable_bus_axioms OPH.SourceSelectionControls.full_cover_unique_minimum
audit_reusable_bus_axioms OPH.SourceSelectionControls.cover_choice_changes_support

audit_reusable_bus_axioms OPH.SourceConstrainedRead.constrained_remote_read_obstruction
audit_reusable_bus_axioms OPH.SourceConstrainedRead.guaranteed_read_excludes_feasible_cut_words
