import Geometry.SourceReusableBusAxiomAudit
import Geometry.SourceBusScaling
import Geometry.SourceNativeRecords

/-! All new theorems use the existing transitive standard-axiom gate.
Its guarded negative controls reject sorryAx and compiler trust. -/

audit_reusable_bus_axioms OPH.SourceBusScaling.forward_later
audit_reusable_bus_axioms OPH.SourceBusScaling.forward_last
audit_reusable_bus_axioms OPH.SourceBusScaling.carry_error
audit_reusable_bus_axioms OPH.SourceBusScaling.forward_read_error
audit_reusable_bus_axioms OPH.SourceBusScaling.forward_before
audit_reusable_bus_axioms OPH.SourceBusScaling.forward_length
audit_reusable_bus_axioms OPH.SourceBusScaling.sweep_length
audit_reusable_bus_axioms OPH.SourceBusScaling.sweep_archives
audit_reusable_bus_axioms OPH.SourceBusScaling.mass_pos
audit_reusable_bus_axioms OPH.SourceBusScaling.mass_ge_four
audit_reusable_bus_axioms OPH.SourceBusScaling.weight_zero
audit_reusable_bus_axioms OPH.SourceBusScaling.weight_bounds
audit_reusable_bus_axioms OPH.SourceBusScaling.weight_mono
audit_reusable_bus_axioms OPH.SourceBusScaling.rate_bounds
audit_reusable_bus_axioms OPH.SourceBusScaling.first_weight
audit_reusable_bus_axioms OPH.SourceBusScaling.step_weight
audit_reusable_bus_axioms OPH.SourceBusScaling.carry_bound
audit_reusable_bus_axioms OPH.SourceBusScaling.sweep_contraction
audit_reusable_bus_axioms OPH.SourceBusScaling.cleaning_length
audit_reusable_bus_axioms OPH.SourceBusScaling.readCycle_length
audit_reusable_bus_axioms OPH.SourceBusScaling.cleaning_contraction
audit_reusable_bus_axioms OPH.SourceBusScaling.cleanup_bound
audit_reusable_bus_axioms OPH.SourceBusScaling.sweep_zero
audit_reusable_bus_axioms OPH.SourceBusScaling.cleaning_archives
audit_reusable_bus_axioms OPH.SourceBusScaling.rate_power_bound
audit_reusable_bus_axioms OPH.SourceBusScaling.block_rate
audit_reusable_bus_axioms OPH.SourceBusScaling.cleanup_blocks
audit_reusable_bus_axioms OPH.SourceNativeRecords.halve_formula
audit_reusable_bus_axioms OPH.SourceNativeRecords.halve_native
audit_reusable_bus_axioms OPH.SourceNativeRecords.export_value
audit_reusable_bus_axioms OPH.SourceNativeRecords.writeSum_formula
audit_reusable_bus_axioms OPH.SourceNativeRecords.writeSum_native
audit_reusable_bus_axioms OPH.SourceNativeRecords.writeSum_length
audit_reusable_bus_axioms OPH.SourceNativeRecords.writeSum_decoded
audit_reusable_bus_axioms OPH.SourceNativeRecords.mean_range
audit_reusable_bus_axioms OPH.SourceNativeRecords.run_range
audit_reusable_bus_axioms OPH.SourceNativeRecords.growth_lower
audit_reusable_bus_axioms OPH.SourceNativeRecords.raw_growth_obstruction
audit_reusable_bus_axioms OPH.SourceNativeRecords.schedule_dependence
